package cadastrocliente;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.text.*;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
public class CadastroCliente extends JFrame{
JLabel rotcep,rottel,rotcpf,rotdat,rotnome,rotbar,rotcid,rotest,rotcnpj,rotinsc,rotemail,rotrua,rotnum,rotcomp,rottelcel,rotrg,rottelcom,rottit,rotstat,rotobs;
JFormattedTextField cep,tel,cpf,data,cnpj,telcel,rg,telcom;
JTextField nome,bairro,cidade,estado,insc,email,rua,num,comp,obs;
MaskFormatter masccep,masctel,masccpf,mascnome,mascdata,masccnpj,masctelcel,mascrg,masctelcom;
JRadioButton pesfis,pesjur;
JButton bot;
ImageIcon icon;
   public CadastroCliente(){
         super("Cadastro de Clientes");
      
         Container tela = getContentPane();
       setLayout(null);
       icon = new ImageIcon("user2.png");
       bot = new JButton("Cadastar",icon);
       rotobs = new JLabel("Observações:");
       pesfis = new JRadioButton("Pessoa Física");
       pesjur = new JRadioButton("Pessoa Jurídica");
       rottit= new JLabel("Cadastro de Clientes");
       rotrg = new JLabel("RG:");
       rotnome = new JLabel("Nome:");
       rotcep = new JLabel("CEP:");
       rottel = new JLabel("Telefone Residencial:");
       rotcpf = new JLabel("CPF:");
       rotdat = new JLabel("Data de Nascimento:");
       rotstat= new JLabel("Status:");
       rottelcel = new JLabel("Telefone Celular:");
       rotbar = new JLabel("Bairro:");
        rotcid = new JLabel("Cidade:");
         rotest = new JLabel("Estado:");
          rotcnpj = new JLabel("CNPJ:");
           rotinsc = new JLabel("Inscrição Estadual:");
            rotemail= new JLabel("Email:");
             rotrua = new JLabel("Rua:");
              rotnum = new JLabel("Número:");
               rotcomp = new JLabel("Complemento:");
       pesfis.setBounds(170, 40,120, 20);
       pesjur.setBounds(500, 40,120, 20);
               rottelcom = new JLabel("Telefone Comercial:");
               rotobs.setBounds(80,480,100,20);
               bot.setBounds(850,450,130,40);
       rottit.setBounds(5,10,200,20); 
rotstat.setBounds(130,40,100,20);       
               rotrg.setBounds(780,320,100,20);        
       rotcep.setBounds(770,160,100,20);
       rottelcom.setBounds(55,240,120,20);
       rotcpf.setBounds(770,280,100,20);
       rotdat.setBounds(680,360,120,20);
       rotnome.setBounds(130,80,100,20);
       rotbar.setBounds(130,120,100,20);
        rotcid.setBounds(125,160,100,20);
        rotest.setBounds(125,200,100,20);
        rotcnpj.setBounds(130,280,100,20);
        rotinsc.setBounds(60,320,120,20);
        rotemail.setBounds(130,360,100,20);
        rotrua.setBounds(770,40,100,20);
        rotnum.setBounds(750,80,100,20);
        rotcomp.setBounds(715,120,100,20);
        rottelcel.setBounds(700,240,100,20);
        rottel.setBounds(675,200,125,20);
        rottit.setFont(new Font("Arial",Font.BOLD,20));
        rottit.setForeground(new Color(35,142,104));
       try{
           masctelcom = new MaskFormatter ("(##)#####-###"); 
          masccnpj = new MaskFormatter("##.##.##/####-##");    
           masccep = new MaskFormatter("#####-###");
           masctel = new MaskFormatter("(##)####-####");
           masccpf = new MaskFormatter("###.###.###-##"); 
           mascdata = new MaskFormatter("##/##/####");
           masctelcel = new MaskFormatter("(##)#####-####");
           mascrg = new MaskFormatter("##.###.###-#"); 
           masccep.setPlaceholderCharacter('_');
           masctel.setPlaceholderCharacter('_');
           masccpf.setPlaceholderCharacter('_');
           mascdata.setPlaceholderCharacter('_');
           masccnpj.setPlaceholderCharacter('_');
           masctelcel.setPlaceholderCharacter('_');
           mascrg.setPlaceholderCharacter('_');
           masctelcom.setPlaceholderCharacter('_');
       }
       catch(ParseException excp){}
       obs = new JTextField(10);
       cep = new JFormattedTextField(masccep);
tel = new JFormattedTextField(masctel);
cpf = new JFormattedTextField(masccpf);
data = new JFormattedTextField(mascdata);
cnpj = new JFormattedTextField(masccnpj);
rg = new JFormattedTextField(mascrg);
telcel = new JFormattedTextField(masctelcel);
telcom = new JFormattedTextField(masctelcom);
rua = new JTextField(10);
num = new JTextField(10);
estado = new JTextField(2);
bairro = new JTextField(10);
cidade = new JTextField(10);
comp = new JTextField(10);
email = new JTextField(20);
insc = new JTextField(10);
nome = new JTextField(20);
cep.setBounds(800,160,70,20);
tel.setBounds(800,200,100,20);
cpf.setBounds(800,280,100,20);
data.setBounds(800,360,100,20);
cnpj.setBounds(170,280,100,20);
telcel.setBounds(800,240,100,20);
telcom.setBounds(170,240,100,20);
rua.setBounds(800,40,250,20);
num.setBounds(800,80,50,20);
estado.setBounds(170,200,20,20);
bairro.setBounds(170,120,250,20);
cidade.setBounds(170,160,250,20);
comp.setBounds(800,120,250,20);
email.setBounds(170,360,300,20);
obs.setBounds(170,390,500,200);
insc.setBounds(170,320,200,20);
rg.setBounds(800,320,100,20);
nome.setBounds(170,80,250,20);
tela.add(bot);
tela.add(obs);
tela.add(rotobs);
tela.add(rotstat);
tela.add(pesfis);
tela.add(pesjur);
tela.add(rotinsc);
tela.add(rottelcel);
tela.add(rotemail);
tela.add(rotrua);
tela.add(rotnum);
tela.add(rotest);
tela.add(rotbar);
tela.add(rottel);
tela.add(rotcomp);
tela.add(rotcid);
tela.add(rotcep);
tela.add(rotcnpj);
tela.add(rotcpf);
tela.add(rotdat);
tela.add(rotnome);
tela.add(telcel);
tela.add(email);
tela.add(num);
tela.add(rua);
tela.add(estado);
tela.add(bairro);
tela.add(cidade);
tela.add(insc);
tela.add(cep);
tela.add(tel);
tela.add(cpf);
tela.add(data);
tela.add(cnpj);
tela.add(comp);
tela.add(rotrg);
tela.add(rg);
tela.add(nome);
tela.add(rottelcom);
tela.add(telcom);
tela.add(rottit);
 setResizable(false);
setSize(1100,650);
setVisible(true);
   }
    public static void main(String[] args) {
    
    CadastroCliente app = new CadastroCliente();
    app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   
    }
    
}
   
